server:
  port:
    8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
            http://${keycloak.host}:${keycloak.port}/realms/${keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Origin, RETAIN_LAST
        - AddResponseHeader=Access-Control-Origin, *
      routes:
        - id: auth
          uri: http://${keycloak.host}:${keycloak.port}
          predicates:
            - Path=/openid-connect/**
          filters:
            - RewritePath=/openid-connect, /realms/${keycloak.realm}/protocol/openid-connect

        - id: portal
          uri: http://localhost:8082
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal, /
            - Portal=

        - id: logist
          uri: http://localhost:8083
          predicates:
            - Path=/logist/**
          filters:
            - RewritePath=/logist, /

        - id: driver
          uri: http://localhost:8084
          predicates:
            - Path=/driver/**
          filters:
            - RewritePath=/driver, /

        - id: dwh
          uri: http://localhost:8085
          predicates:
            - Path=/dwh/**
          filters:
            - RewritePath=/dwh, /

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

keycloak:
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEY_CLOAK_PASSWORD}
  realm: ${KEYCLOAK_REALM}
  host: localhost
  port: 8080

