server:
  port:
    8085
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

spring:
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092

  sql:
    init:
      mode: never
  datasource:
    username: postgres
    password: 124491
    url: jdbc:postgresql://localhost:5432/dwhdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

