server:
  port:
    8082
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/

spring:
  sql:
    init:
      mode: never
  datasource:
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
    url: ${SPRING_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
            http://${keycloak.host}:${keycloak.port}/realms/${keycloak.realm}/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

adata:
  token: Token 7bfee02a63ecf31a6233e7f8c9c7827d8fd262e0

keycloak:
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEY_CLOAK_PASSWORD}
  realm: ${KEYCLOAK_REALM}
  host: localhost
  port: 8080

